version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: redmine-example-01-postgres
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - redmine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redmine -d redmine"]
      interval: 10s
      timeout: 5s
      retries: 5

  redmine:
    image: redmine:5.0
    container_name: redmine-example-01-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_HOST: postgres
      REDMINE_DB_PORT: 5432
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine123
      REDMINE_SECRET_KEY_BASE: "example-secret-key-for-development-only"
    ports:
      - "3000:3000"
    networks:
      - redmine-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: redmine-example-01-adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - redmine-network
    restart: unless-stopped

networks:
  redmine-network:
    driver: bridge
